flow package require MemGen
flow run /MemGen/MemoryGenerator_BuildLib {
VENDOR           Nangate
RTLTOOL          OasysRTL
TECHNOLOGY       045nm
LIBRARY          DPRAM
MODULE           DPRAM
OUTPUT_DIR       ./.
FILES {
  { FILENAME ./DPRAM.v FILETYPE Verilog MODELTYPE generic PARSE 1 PATHTYPE relative STATICFILE 1 VHDL_LIB_MAPS work }
}
VHDLARRAYPATH    {}
WRITEDELAY       0.1
INITDELAY        1
READDELAY        1.1
VERILOGARRAYPATH {}
INPUTDELAY       0.01
TIMEUNIT         1ns
WIDTH            width
AREA             0
RDWRRESOLUTION   UNKNOWN
WRITELATENCY     1
READLATENCY      1
DEPTH            words
PARAMETERS {
  { PARAMETER words      TYPE hdl IGNORE 0 MIN {} MAX {} DEFAULT 0 }
  { PARAMETER width      TYPE hdl IGNORE 0 MIN {} MAX {} DEFAULT 0 }
  { PARAMETER addr_width TYPE hdl IGNORE 0 MIN {} MAX {} DEFAULT 0 }
}
PORTS {
  { NAME rd MODE Read  }
  { NAME wr MODE Write }
}
PINMAPS {
  { PHYPIN Q    LOGPIN DATA_OUT     DIRECTION out WIDTH width      PHASE {} DEFAULT {} PORTS rd }
  { PHYPIN RCLK LOGPIN CLOCK        DIRECTION in  WIDTH 1.0        PHASE 1  DEFAULT {} PORTS rd }
  { PHYPIN WCLK LOGPIN CLOCK        DIRECTION in  WIDTH 1.0        PHASE 1  DEFAULT {} PORTS wr }
  { PHYPIN RCSN LOGPIN READ_ENABLE  DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS rd }
  { PHYPIN WCSN LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS wr }
  { PHYPIN WEN  LOGPIN WRITE_ENABLE DIRECTION in  WIDTH 1.0        PHASE 0  DEFAULT {} PORTS wr }
  { PHYPIN D    LOGPIN DATA_IN      DIRECTION in  WIDTH width      PHASE {} DEFAULT {} PORTS wr }
  { PHYPIN RA   LOGPIN ADDRESS      DIRECTION in  WIDTH addr_width PHASE {} DEFAULT {} PORTS rd }
  { PHYPIN WA   LOGPIN ADDRESS      DIRECTION in  WIDTH addr_width PHASE {} DEFAULT {} PORTS wr }
}

}
